In [34]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
df=pd.read_csv("weight-height (1).csv")
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

# Encoding Gender

In [35]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df1 = df.copy()
df1.Gender = le.fit_transform(df[['Gender']])
df1.head()

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

# Data split

In [36]:
x = df1.drop('Weight', axis=1)
y = df1['Weight']

In [37]:
x.head()

Gender     Height
0       1  73.847017
1       1  68.781904
2       1  74.110105
3       1  71.730978
4       1  69.881796

In [38]:
y.head()

0    241.893563
1    162.310473
2    212.740856
3    220.042470
4    206.349801
Name: Weight, dtype: float64

In [39]:
len(df)

8555

In [40]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x , y, test_size=.30)

In [41]:
xtrain.head() #70% train data

Gender     Height
2253       1  65.094065
96         1  71.701234
4891       1  71.585524
1963       1  68.878553
3071       1  68.647412

In [42]:
xtest.head() #30% test data

Gender     Height
8525       0  66.394343
6496       0  61.924197
7140       0  64.846459
2763       1  68.457061
1570       1  65.924741

# Regression using linear Regression

In [43]:
from sklearn.linear_model import LinearRegression
reg= LinearRegression()
reg.fit(xtrain, ytrain) #train data using Linear Regression
reg.predict(xtest) #test data using Linear Regression

array([151.70473438, 125.14859062, 142.50910067, ..., 193.23855602,
       210.25548248, 208.85913098])

In [44]:
#training score of Linear Regression
reg.score(xtrain, ytrain)

0.9000273243835963

In [45]:
#testing accuracy of Linear Regression
reg.score(xtest, ytest)

0.8996236250624523

In [46]:
#Using MSE for Testing Linear Regression
from sklearn.metrics import mean_squared_error, mean_absolute_error
mse_reg = mean_squared_error(ytest, reg.predict(xtest))
mse_reg

104.08613648778189

# Using KNN Regression

In [47]:

from sklearn.neighbors import KNeighborsRegressor
KNN = KNeighborsRegressor(n_neighbors=93)

KNN.fit(xtrain, ytrain)

KNeighborsRegressor(n_neighbors=93)

In [48]:
KNN.predict(xtest)

array([152.23667192, 125.51971069, 143.02450971, ..., 194.60725787,
       208.83273894, 208.0846218 ])

In [49]:
#training score KNN
KNN.score(xtrain, ytrain)

0.8984375990840507

In [50]:
#testing accuracy of KNN
KNN.score(xtest, ytest)

0.8972892545635466

In [51]:
#Using MSE for Testing KNN Regression
mse_knn = mean_squared_error(ytest, KNN.predict(xtest))
mse_knn

106.5067818489371

In [52]:
#Here, Accuracy of KNN is less than the accuraccy of Linear Regression

# KNN for Classification

In [53]:
#Data split
x2 = df1.drop('Gender', axis=1)
y2 = df1['Gender']
x2.head()

Height      Weight
0  73.847017  241.893563
1  68.781904  162.310473
2  74.110105  212.740856
3  71.730978  220.042470
4  69.881796  206.349801

In [54]:
y2.head()

0    1
1    1
2    1
3    1
4    1
Name: Gender, dtype: int64

In [55]:
x2train, x2test, y2train, y2test = train_test_split(x2 , y2, test_size=.30) #train 70%, test 30%
x2train.head()

Height      Weight
768   69.553614  203.811091
4470  72.037268  209.934708
1930  65.922822  175.424032
6825  62.576080  111.379474
552   70.663323  195.626319

In [56]:
x2test.head()

Height      Weight
2289  67.803604  158.347246
1189  68.256645  201.868143
4408  67.841363  179.647844
2985  65.775658  170.219947
1541  65.934431  162.549680

In [57]:
#Prediction using KNN Classification
from sklearn.neighbors import KNeighborsClassifier
KNN_cls = KNeighborsClassifier(n_neighbors=93)

KNN_cls.fit(x2train, y2train)

KNeighborsClassifier(n_neighbors=93)

In [58]:
KNN_cls.predict(x2test)

array([0, 1, 1, ..., 0, 1, 0])

In [59]:
#training score of KNN Classifier
KNN_cls.score(x2train, y2train)

0.9178356713426854

In [60]:
#testing accuracy of KNN Classifier
KNN_cls.score(x2test, y2test)

0.9142968445656409